### ISSUE TITLE
Add support for default (main) branch and production deploys

### ISSUE THREAD

**Issue by ankushg** [zentered/cloudflare-preview-url#15]
**Is your feature request related to a problem? Please describe.**
I would like to perform actions like purging my Cloudflare cache and running Lighthouse tests when my default branch (`main`) is deployed, but the plugin doesn't currently support fetching data for production (non-preview) deployments.

**Describe the solution you'd like**
Github Action should be able to detect when a deploy for the default-branch has succeeded, and provide the url, even if it's a production (non-preview) deployment.

**Additional context**
I see that the current plugin behavior 
- filters based on `environment === "preview"`
- asserts against branch names (which makes things tricky when you have multiple deploys per branch)

At the same time, the Cloudflare API also provides a `deployment_trigger.metadata.commit_hash` property. 

Is it possible to allow the user to
- tell the plugin to match via commit hash instead of branch name, 
- tell the plugin which deploy environment to check (e.g., production)

**Comment by PatrickHeneise** [comment]
Thanks for raising the issue. The production url is usually known, so I guess you're more interested in the "wait until ready" part. Can you provide a change that checks if the branch is `main` to use the deployment environment `production` instead of preview, to fetch the latest production deploy?

**Comment by ankushg** [comment]
Sure thing

Is there a reason to be using branch names instead of commit hashes? Wouldn't the `main` branch have multiple deployments?

**Comment by PatrickHeneise** [comment]
Just simplicity at the time. The preview url doesn't change once it's creates for a PR, so I found it easier to look for branches instead of SHAs, but feel free to change if you think it works better.
