### ISSUE TITLE
Authorization not working

### ISSUE THREAD

**Issue by VanishMax** [zentered/cloudflare-preview-url#40]
**Describe the bug**
I've tried to use the Action with all provided secret keys, but the authorization on CloudFlare didn't work.

**To Reproduce**
1. Do everything like in the docs. The API token of CloudFlare is made only to access the Pages of the account, read access.

**Expected behavior**
The action works

**Additional context**
The action calls the `https://api.cloudflare.com/client/v4/accounts/***/pages/projects/project-name/deployments` API method of CloudFlare with the `X-Auth-Key` and `X-Auth-email` headers. This request returns the 400 error with 10000 (Unauthorized) status inside the return data.

I've tried requesting this method from Postman, and here's what I've found. As it is said in [the CloudFlare community](https://community.cloudflare.com/t/always-authentication-error-10000-when-using-api-for-getting-dns-record-id/185769), the `Authorization` header works better than other header when we access the CloudFlare API.

I propose changing this logic in the action code. In this case, the `CLOUDFLARE_ACCOUNT_EMAIL` variable won't be needed at all.

I can make the PR solving this issue, if you agree with the changes.

**Comment by PatrickHeneise** [comment]
Could you prepare a PR for that?
