### ISSUE TITLE
Updating actions to Node 16 and versioning of the @actions/core package to 

### ISSUE THREAD

**Issue by kzwt-capco** [zentered/cloudflare-preview-url#49]
**Action is using deprecated Node.js 12 commands**
When running our application I encountered the build warning:
This action is using Node.js 12 which is no longer supported by Github Workflow which throws the following error:
"Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: zentered/cloudflare-preview-url@v1.3.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/."

If not updated, the warning will throw the error in June 2023, according to Github (https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

**Expected change**
Node version in action.yaml file needs to be changed: line 29 to "using: node16".
As well as in package.json dependency in line 50 to " "@actions/core": "^1.10.0"

 **Additional context**
Please see the file below for reference.
![image](https://user-images.githubusercontent.com/92172604/216400957-c54176a7-1f85-49a9-bf26-ab5b5ff916f7.png)

**Comment by PatrickHeneise** [comment]
Thanks for the reminder, I updated the node version and all packages. Let me know if there's an issue.
