### ISSUE TITLE
Not finding deployments

### ISSUE THREAD

**Issue by joshghent** [zentered/cloudflare-preview-url#57]
**Describe the bug**
Thanks for the great project!
For some reason it's not finding deployments for my pull requests.
Log here: https://github.com/joshghent/blog/actions/runs/7298978898/job/19890930713?pr=957

```
Found 25 deployments
Found 0 matching builds
Error: []
Error: no matching builds found
```

Appreciate if you could point me in the right direction to sort this 💙 

**Expected behavior**
To find deployments

**Additional context**
Using V1.4.0

**Comment by PatrickHeneise** [comment]
Thanks @joshghent for the report.

The Action looks for the current branch metadata, as far as I can tell, your pull-request checks runs on `main` (`master`) but should be running on the feature-branch instead. Try this:

```
on:
  push:
    branches:
      - '**'
      - '!main'
```

That'll run the PR on the feature branch instead and use the right metadata.

**Comment by PatrickHeneise** [comment]
Discussed & resolved here: https://github.com/joshghent/blog/pull/957#issuecomment-1867940568
